version: '3.7'
services:
  api:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - .:/code
    - logvolume01:/var/log
    container_name: pantry
    environment:
      - DEPLOYMENT_ENV=local
volumes:
  logvolume01: {}
